namespace jreng::Colours
{
/**
 * @brief Returns a random vivid JUCE colour.
 *
 * Generates a colour in HSB space with high saturation and brightness
 * to ensure vividness.
 *
 * @return A randomly generated vivid juce::Colour.
 */
inline static juce::Colour getRandomVivid()
{
    // Random hue across the full circle [0, 1)
    const float hue = juce::Random::getSystemRandom().nextFloat();

    // Keep saturation and brightness in the vivid range
    const float saturation = juce::jmap (juce::Random::getSystemRandom().nextFloat(),
                                         0.7f,
                                         1.0f);// 70–100%
    const float brightness = juce::jmap (juce::Random::getSystemRandom().nextFloat(),
                                         0.8f,
                                         1.0f);// 80–100%

    return juce::Colour::fromHSV (hue, saturation, brightness, 1.0f);
}

/**
 * @brief Returns a vivid JUCE colour by cycling through a configurable number of distinct hues.
 *
 * Each call advances the hue index and wraps around after @p steps.
 * You can also specify a starting hue offset (e.g. 0.0f for red).
 *
 * @param steps Number of distinct hues in the cycle (default 8).
 * @param startHue Starting hue offset in [0.0f, 1.0f) (default 0.0f = red).
 * @return A vivid juce::Colour from the cyclic palette.
 */
inline static juce::Colour getCyclicVivid (int steps = 8, float startHue = 0.0f, float alpha = 1.0f)
{
    static int counter = 0;

    if (steps <= 0)
        steps = 1;// avoid division by zero

    // Evenly spaced hue in [0, 1), offset by startHue
    float hue = startHue + (counter++ % steps) / static_cast<float> (steps);

    // Wrap hue into [0, 1)
    if (hue >= 1.0f)
        hue -= 1.0f;

    // Strong saturation and brightness for vivid colours
    constexpr float saturation = 0.9f;
    constexpr float brightness = 0.95f;

    return juce::Colour::fromHSV (hue, saturation, brightness, 1.0f).withAlpha (alpha);
}

/**
 * @brief Returns a random fully saturated and bright JUCE colour.
 *
 * Generates a colour in HSB space with:
 * - Random hue in [0, 1).
 * - Saturation fixed at 1.0 (fully saturated).
 * - Brightness fixed at 1.0 (maximum brightness).
 * - Alpha fixed at 0xff (fully opaque).
 *
 * @return A randomly generated vivid juce::Colour.
 */
inline static juce::Colour getRandom()
{
    const float hue { juce::Random().nextFloat() };
    const float saturation { 1.0f };
    const float brightness { 1.0f };
    const juce::uint8 alpha { 0xff };

    return juce::Colour { hue, saturation, brightness, alpha };
}

/**
 * @brief Creates a vertical colour gradient for a given shape.
 *
 * The gradient is generated by adjusting the lightness of the base colour
 * to create highlight and shadow variations. The gradient can be oriented
 * from bright-to-dark or dark-to-bright.
 *
 * @param shapeBounds The bounds of the shape to which the gradient will be applied.
 * @param colour The base colour for the gradient.
 * @param highlightLightness Multiplier for the highlight colour lightness (default 1.5).
 * @param shadowLightness Multiplier for the shadow colour lightness (default 0.72).
 * @param bottomOffset Offset from the bottom of the shape for the gradient end (default 0.0f).
 * @param brightToDark If true, gradient goes from highlight at the top to shadow at the bottom;
 *                     if false, the direction is reversed.
 *
 * @return A juce::ColourGradient representing the vertical gradient.
 */
inline static juce::ColourGradient getVerticalGradient (const juce::Rectangle<float>& shapeBounds,
                                                        juce::Colour colour,
                                                        float highlightLightness = 1.5f,
                                                        float shadowLightness = 0.72f,
                                                        float bottomOffset = 0.0f,
                                                        bool brightToDark = true) noexcept
{
    auto colour1 { colour.withMultipliedLightness (brightToDark ? highlightLightness : shadowLightness) };
    auto colour2 { colour.withMultipliedLightness (brightToDark ? shadowLightness : highlightLightness) };
    return juce::ColourGradient::vertical (colour1, shapeBounds.getY(), colour2, shapeBounds.getBottom() - bottomOffset);
}

/**
 * \brief Look up the exact human-readable name for a given juce::Colour.
 *
 * Parses the embedded JSON lookup table (cached on first call) and
 * compares the colour's RGB value against the "hex" entries in the table.
 *
 * \param colour The juce::Colour to look up.
 * \return The matching name string if found, or an empty string if no exact match exists.
 *
 * \note Conversion uses getARGB() masked to RGB and formatted as #RRGGBB.
 * \warning Returns empty if the colour is not exactly present in the table.
 */
inline static juce::String getName (juce::Colour colour)
{
    static juce::var parsed = juce::JSON::parse (
        juce::String::fromUTF8 (names_json, names_jsonSize));

    if (! parsed.isObject())
        return {};

    auto* obj = parsed.getDynamicObject();
    auto colors = obj->getProperty ("colors");

    if (! colors.isArray())
        return {};

    // Convert Colour to #RRGGBB
    juce::String targetHex = "#"
                             + juce::String::toHexString (colour.getARGB() & 0x00FFFFFF)
                                   .paddedLeft ('0', 6)
                                   .toUpperCase();

    for (auto& c : *colors.getArray())
    {
        if (auto* colorObj = c.getDynamicObject())
        {
            juce::String hex = colorObj->getProperty ("hex").toString().toUpperCase();
            if (hex == targetHex)
                return colorObj->getProperty ("name").toString();
        }
    }

    return {};
}

/**
 * \brief Find the nearest human-readable name for a given juce::Colour.
 *
 * Parses the embedded JSON lookup table (cached on first call) and
 * computes the squared Euclidean distance in RGB space between the input
 * colour and each entry in the table. Returns the name of the closest match.
 *
 * \param colour The juce::Colour to approximate.
 * \return The name of the closest colour in the table.
 *
 * \note Always returns some name, even if the colour is not an exact match.
 * \see getName for exact matching.
 */
inline static juce::String getNearestName (juce::Colour colour)
{
    static juce::var parsed = juce::JSON::parse (
        juce::String::fromUTF8 (names_json, names_jsonSize));

    if (! parsed.isObject())
        return {};

    auto* obj = parsed.getDynamicObject();
    auto colors = obj->getProperty ("colors");
    if (! colors.isArray())
        return {};

    juce::String bestName;
    int bestDist = std::numeric_limits<int>::max();

    for (auto& c : *colors.getArray())
    {
        if (auto* colorObj = c.getDynamicObject())
        {
            juce::String hex = colorObj->getProperty ("hex").toString();
            juce::Colour tableColour = juce::Colour::fromString (hex);

            int dr = colour.getRed() - tableColour.getRed();
            int dg = colour.getGreen() - tableColour.getGreen();
            int db = colour.getBlue() - tableColour.getBlue();
            int dist2 = dr * dr + dg * dg + db * db;

            if (dist2 < bestDist)
            {
                bestDist = dist2;
                bestName = colorObj->getProperty ("name").toString();
            }
        }
    }

    return bestName;
}

/**
 * \brief Get the nearest colour name, formatted in camelCase.
 *
 * Wraps getNearestName() and applies jreng::String::lowerFirstChar() and
 * jreng::String::toCamelCase() to produce a formatted identifier-style string.
 *
 * \param colour The juce::Colour to approximate.
 * \return The nearest colour name, formatted in camelCase.
 *
 * \see getNearestName
 */
inline static juce::String getNearestNameFormatted (juce::Colour colour)
{
    return jreng::String::toCamelCase (jreng::String::lowerFirstChar (getNearestName (colour)));
}

}
