#include "jreng_freetype.h"

// FreeType compile definitions
#define FT2_BUILD_LIBRARY
#define FT_ERR_PREFIX  FT_Err_

// FreeType source — single-file build entry points
#include "freetype/src/autofit/autofit.c"
#include "freetype/src/base/ftbase.c"
#include "freetype/src/base/ftbbox.c"
#include "freetype/src/base/ftbdf.c"
#include "freetype/src/base/ftbitmap.c"
#include "freetype/src/base/ftcid.c"
#include "freetype/src/base/ftfstype.c"
#include "freetype/src/base/ftgasp.c"
#include "freetype/src/base/ftglyph.c"
#include "freetype/src/base/ftgxval.c"
#include "freetype/src/base/ftinit.c"
#include "freetype/src/base/ftmm.c"
#include "freetype/src/base/ftotval.c"
#include "freetype/src/base/ftpatent.c"
#include "freetype/src/base/ftpfr.c"
#include "freetype/src/base/ftstroke.c"
#include "freetype/src/base/ftsynth.c"
#include "freetype/src/base/fttype1.c"
#include "freetype/src/base/ftwinfnt.c"
#include "freetype/src/bdf/bdf.c"
#include "freetype/src/cache/ftcache.c"
#include "freetype/src/cff/cff.c"
#include "freetype/src/cid/type1cid.c"
#include "freetype/src/lzw/ftlzw.c"
#include "freetype/src/pcf/pcf.c"
#include "freetype/src/pfr/pfr.c"
#include "freetype/src/psaux/psaux.c"
#include "freetype/src/pshinter/pshinter.c"
#include "freetype/src/psnames/psnames.c"
#include "freetype/src/raster/raster.c"
#include "freetype/src/sdf/sdf.c"
#include "freetype/src/sfnt/sfnt.c"
#include "freetype/src/smooth/smooth.c"
#include "freetype/src/svg/svg.c"
#include "freetype/src/truetype/truetype.c"
#include "freetype/src/type1/type1.c"
#include "freetype/src/type42/type42.c"
#include "freetype/src/winfonts/winfnt.c"

// System interface
#include "freetype/src/base/ftsystem.c"
#include "freetype/src/base/ftdebug.c"
