#pragma once

namespace jreng
{
/*____________________________________________________________________________*/

namespace Graphics
{
/*____________________________________________________________________________*/

/**
 * @brief Returns a random vivid JUCE colour.
 *
 * Generates a colour in HSB space with high saturation and brightness
 * to ensure vividness.
 *
 * @return A randomly generated vivid juce::Colour.
 */
inline static juce::Colour getRandomVividColour()
{
    // Random hue across the full circle [0, 1)
    const float hue = juce::Random::getSystemRandom().nextFloat();

    // Keep saturation and brightness in the vivid range
    const float saturation = juce::jmap (juce::Random::getSystemRandom().nextFloat(),
                                         0.7f,
                                         1.0f);// 70–100%
    const float brightness = juce::jmap (juce::Random::getSystemRandom().nextFloat(),
                                         0.8f,
                                         1.0f);// 80–100%

    return juce::Colour::fromHSV (hue, saturation, brightness, 1.0f);
}

/**
 * @brief Returns a vivid JUCE colour by cycling through a configurable number of distinct hues.
 *
 * Each call advances the hue index and wraps around after @p steps.
 * You can also specify a starting hue offset (e.g. 0.0f for red).
 *
 * @param steps Number of distinct hues in the cycle (default 8).
 * @param startHue Starting hue offset in [0.0f, 1.0f) (default 0.0f = red).
 * @return A vivid juce::Colour from the cyclic palette.
 */
inline static juce::Colour getCyclicVividColour (int steps = 8, float startHue = 0.0f, float alpha = 1.0f)
{
    static int counter = 0;

    if (steps <= 0)
        steps = 1;// avoid division by zero

    // Evenly spaced hue in [0, 1), offset by startHue
    float hue = startHue + (counter++ % steps) / static_cast<float> (steps);

    // Wrap hue into [0, 1)
    if (hue >= 1.0f)
        hue -= 1.0f;

    // Strong saturation and brightness for vivid colours
    constexpr float saturation = 0.9f;
    constexpr float brightness = 0.95f;

    return juce::Colour::fromHSV (hue, saturation, brightness, 1.0f).withAlpha (alpha);
}

/**
 * @brief Returns a random fully saturated and bright JUCE colour.
 *
 * Generates a colour in HSB space with:
 * - Random hue in [0, 1).
 * - Saturation fixed at 1.0 (fully saturated).
 * - Brightness fixed at 1.0 (maximum brightness).
 * - Alpha fixed at 0xff (fully opaque).
 *
 * @return A randomly generated vivid juce::Colour.
 */
inline static juce::Colour getRandomColour()
{
    const float hue { juce::Random().nextFloat() };
    const float saturation { 1.0f };
    const float brightness { 1.0f };
    const juce::uint8 alpha { 0xff };

    return juce::Colour { hue, saturation, brightness, alpha };
}

/**
 * @brief Creates a vertical colour gradient for a given shape.
 *
 * The gradient is generated by adjusting the lightness of the base colour
 * to create highlight and shadow variations. The gradient can be oriented
 * from bright-to-dark or dark-to-bright.
 *
 * @param shapeBounds The bounds of the shape to which the gradient will be applied.
 * @param colour The base colour for the gradient.
 * @param highlightLightness Multiplier for the highlight colour lightness (default 1.5).
 * @param shadowLightness Multiplier for the shadow colour lightness (default 0.72).
 * @param bottomOffset Offset from the bottom of the shape for the gradient end (default 0.0f).
 * @param brightToDark If true, gradient goes from highlight at the top to shadow at the bottom;
 *                     if false, the direction is reversed.
 *
 * @return A juce::ColourGradient representing the vertical gradient.
 */
inline static juce::ColourGradient getVerticalGradient (const juce::Rectangle<float>& shapeBounds,
                                                        juce::Colour colour,
                                                        float highlightLightness = 1.5f,
                                                        float shadowLightness = 0.72f,
                                                        float bottomOffset = 0.0f,
                                                        bool brightToDark = true) noexcept
{
    auto colour1 { colour.withMultipliedLightness (brightToDark ? highlightLightness : shadowLightness) };
    auto colour2 { colour.withMultipliedLightness (brightToDark ? shadowLightness : highlightLightness) };
    return juce::ColourGradient::vertical (colour1, shapeBounds.getY(), colour2, shapeBounds.getBottom() - bottomOffset);
}

/*____________________________________________________________________________*/
inline static void drawRect (juce::Graphics& g,
                             const juce::Rectangle<int>& area,
                             juce::Colour colour = juce::Colours::magenta)
{
    g.setColour (colour);
    g.drawRect (area);
}

inline static void fillRect (juce::Graphics& g,
                             const juce::Rectangle<int>& area,
                             juce::Colour colour = juce::Colours::magenta)
{
    g.setColour (colour);
    g.fillRect (area);
}

inline static void drawRoundedRectangle (juce::Graphics& g, const juce::Rectangle<float>& area, juce::Colour colour = juce::Colours::magenta, float cornerSize = 4.0f, float lineThickness = 2.0f)
{
    g.setColour (colour);
    g.drawRoundedRectangle (area.toFloat().reduced (0.5f * lineThickness), cornerSize, lineThickness);
}

inline static void fillRoundedRectangle (juce::Graphics& g, const juce::Rectangle<float>& area, juce::Colour colour = juce::Colours::magenta, float cornerSize = 4.0f)
{
    g.setColour (colour);
    g.fillRoundedRectangle (area.toFloat(), cornerSize);
}

inline static void drawRoundedRectangle (juce::Graphics& g, const juce::Rectangle<int>& area, juce::Colour colour = juce::Colours::magenta, float cornerSize = 4.0f, float lineThickness = 2.0f)
{
    drawRoundedRectangle (g, area.toFloat(), colour, cornerSize, lineThickness);
}

inline static void fillRoundedRectangle (juce::Graphics& g, const juce::Rectangle<int>& area, juce::Colour colour = juce::Colours::magenta, float cornerSize = 4.0f)
{
    fillRoundedRectangle (g, area.toFloat(), colour, cornerSize);
}

inline static void drawBounds (juce::Graphics& g, juce::Component* component, juce::Colour colour = juce::Colours::magenta)
{
    if (component)
        Graphics::drawRect (g, component->getLocalBounds(), colour);
}

inline static void drawChildrenBounds (juce::Graphics& g, juce::Component* parent, float opacity = 1.0f)
{
    if (parent)
    {
        auto& children { parent->getChildren() };

        std::for_each (children.begin(), children.end(), [&] (auto& child)
                       {
                           if (child)
                           {
                               float hue { Value::normalise<float> (children.indexOf (child), 0, children.size()) };
                               float saturation { 1.0f };
                               float brightness (1.0f);
                               float alpha { 0xff };
                               juce::Colour colour { hue, saturation, brightness, alpha };
                               Graphics::drawRect (g, child->getBounds(), colour.withMultipliedAlpha (opacity));
                           }
                       });
    }
}

inline static void writeChildrenBoundsToSVGFile (juce::Component* parent, const juce::File& fileToSave)
{
    juce::StringArray lines;

    for (auto& child : parent->getChildren())
    {
        lines.add (SVG::Format::rect (child->getBounds(), child->getComponentID()));
    }

    auto svg { SVG::File::getStringToWrite (parent->getWidth(),
                                            parent->getHeight(),
                                            lines.joinIntoString ("\n")) };

    fileToSave.replaceWithText (svg);
}

inline static void writeChildrenBoundsToDesktop (juce::Component* parent, const juce::String& filename = { "bounds.svg" })
{
    writeChildrenBoundsToSVGFile (parent, File::getDesktopDirectory().getChildFile (filename));
}

/**_____________________________END OF NAMESPACE______________________________*/
}// namespace Graphics

template<typename ValueType>
using Points = std::vector<juce::Point<ValueType>>;

template<typename ValueType>
using Lines = std::vector<juce::Line<ValueType>>;

template<typename ValueType>
struct Rectangle
{
    static const Lines<ValueType> getLines (const juce::Rectangle<ValueType>& r, bool isCounterClockwise = false)
    {
        Lines<ValueType> lines {
            { r.getTopLeft(), r.getTopRight() },
            { r.getTopRight(), r.getBottomRight() },
            { r.getBottomRight(), r.getBottomLeft() },
            { r.getBottomLeft(), r.getTopLeft() },
        };

        if (isCounterClockwise)
            std::reverse (lines.begin(), lines.end());

        return lines;
    }
};

/*____________________________________________________________________________*/
struct Drawable
{
    static const void draw (juce::Graphics& g,
                            const juce::Path& path,
                            juce::Colour fillColour,
                            juce::Colour strokeColour,
                            float lineThickness = 1.0f,
                            float opacity = 1.0f)
    {
        auto joint { juce::PathStrokeType::curved };
        auto endCap { juce::PathStrokeType::rounded };
        auto strokeType { juce::PathStrokeType (lineThickness, joint, endCap) };

        juce::DrawablePath d;
        d.setPath (path);
        d.setFill (fillColour);
        d.setStrokeType (strokeType);
        d.setStrokeFill (strokeColour);
        d.draw (g, opacity);
    }

    static const void drawWithin (juce::Graphics& g,
                                  const juce::Rectangle<float>& area,
                                  const juce::Path& path,
                                  juce::Colour fillColour,
                                  juce::Colour strokeColour,
                                  float lineThickness = 1.0f,
                                  float opacity = 1.0f)
    {
        auto joint { juce::PathStrokeType::curved };
        auto endCap { juce::PathStrokeType::rounded };
        auto strokeType { juce::PathStrokeType (lineThickness, joint, endCap) };

        juce::DrawablePath d;
        d.setPath (path);
        d.setFill (fillColour);
        d.setStrokeType (strokeType);
        d.setStrokeFill (strokeColour);
        d.drawWithin (g, area, juce::RectanglePlacement::centred, opacity);
    }

    static const void stroke (juce::Graphics& g,
                              const juce::Path& path,
                              juce::Colour strokeColour,
                              float lineThickness = 1.0f,
                              float opacity = 1.0f)
    {
        draw (g, path, juce::Colour(), strokeColour, lineThickness, opacity);
    }

    static const void stroke (juce::Graphics& g,
                              const juce::Rectangle<float>& area,
                              const juce::Path& path,
                              juce::Colour strokeColour,
                              float lineThickness = 1.0f,
                              float opacity = 1.0f)
    {
        drawWithin (g, area, path, juce::Colour(), strokeColour, lineThickness, opacity);
    }

    static const void fill (juce::Graphics& g,
                            const juce::Path& path,
                            juce::Colour fillColour,
                            float lineThickness = 1.0f,
                            float opacity = 1.0f)
    {
        draw (g, path, fillColour, juce::Colour(), lineThickness, opacity);
    }
};

/**_____________________________END OF NAMESPACE______________________________*/
}// namespace jreng
