/**
 * @file jreng_glyph_constraint.h
 * @brief Per-codepoint Nerd Font icon scaling and alignment descriptor.
 *
 * Constraint encodes how a single Nerd Font icon glyph should be scaled,
 * aligned, and padded within a terminal cell at rasterization time.  The
 * constraint is applied by `jreng::Glyph::Packer::rasterizeGlyph()` before the
 * glyph bitmap is stored in the atlas.
 *
 * ### Data source
 * Constraint records are generated by `gen/nf_constraint_gen.py` from Nerd
 * Font patcher v3.4.0 data and stored in `gen/GlyphConstraintTable.cpp`.
 * The lookup function `getConstraint()` maps a Unicode codepoint to its
 * constraint; codepoints not in the table return a default-constructed
 * (inactive) constraint.
 *
 * ### Scale modes
 * | Mode            | Description                                              |
 * |-----------------|----------------------------------------------------------|
 * | `none`          | No resize; glyph is rendered at its natural size.        |
 * | `fit`           | Scale down only to fit the cell; preserve aspect ratio.  |
 * | `cover`         | Scale to fill the cell; preserve aspect ratio.           |
 * | `adaptiveScale` | `fit` if wider than 1 cell, `cover` if narrower.         |
 * | `stretch`       | Stretch independently on both axes; no AR preservation.  |
 *
 * ### Padding model
 * Padding values are fractions of the effective cell dimension:
 * - `padLeft` / `padRight` — fraction of `cellWidth × cellSpan`.
 * - `padTop` / `padBottom` — fraction of `cellHeight`.
 *
 * An additional `iconInset` (≈ 6.18 %) is applied on all sides before the
 * padding, providing a small breathing room between the icon and the cell edge.
 *
 * @note `Constraint` is trivially copyable and stored by value in the
 *       generated lookup table.
 *
 * @see jreng::Glyph::Packer::rasterizeGlyph()
 * @see jreng::Glyph::getConstraint()
 */

#pragma once

#include <cstdint>
#include <type_traits>

namespace jreng::Glyph
{

/**
 * @struct Constraint
 * @brief Scaling, alignment, and padding descriptor for a Nerd Font icon glyph.
 *
 * Applied at rasterization time in `Atlas` before the glyph bitmap is
 * stored in the atlas.  A default-constructed `Constraint` has
 * `scaleMode == ScaleMode::none` and `isActive()` returns `false`, meaning no
 * transformation is applied.
 *
 * @par Trivial copyability
 * `Constraint` is `std::is_trivially_copyable` so it can be stored
 * directly in the generated lookup table without heap allocation.
 *
 * @see jreng::Glyph::Packer::rasterizeGlyph()
 * @see jreng::Glyph::getConstraint()
 */
// Per-glyph scaling and positioning constraint for Nerd Font icons.
// Applied at rasterization time in Atlas before the glyph bitmap
// is stored in the atlas. The constraint controls how the glyph is
// scaled, aligned, and padded within the terminal cell.
//
// Generated by gen/nf_constraint_gen.py from NF patcher v3.4.0 data.
struct Constraint
{
    /**
     * @enum ScaleMode
     * @brief Controls how the glyph is scaled to fit the terminal cell.
     *
     * @see jreng::Glyph::Packer::rasterizeGlyph()
     */
    enum class ScaleMode : uint8_t
    {
        none,          ///< Do not resize; render at natural glyph size.
        fit,           ///< Scale DOWN only to fit cell; preserve aspect ratio.
        cover,         ///< Scale to fill cell; preserve aspect ratio (may clip).
        adaptiveScale, ///< fit if wider than 1 cell, cover if narrower (NF 'pa' flag).
        stretch        ///< Stretch to fill both axes; no aspect ratio preservation.
    };

    /**
     * @enum Align
     * @brief Horizontal or vertical alignment of the scaled glyph within the cell.
     *
     * Used for both `alignH` (horizontal) and `alignV` (vertical) fields.
     */
    enum class Align : uint8_t
    {
        none,   ///< Do not move; use padding-based position.
        start,  ///< Align to left edge (H) or bottom edge (V).
        end,    ///< Align to right edge (H) or top edge (V).
        center  ///< Center in the cell on the respective axis.
    };

    /**
     * @enum HeightRef
     * @brief Reference height used when computing the vertical scale target.
     *
     * - `cell`: Use the full cell height.  Required for powerline / box glyphs
     *   that must tile seamlessly edge-to-edge.
     * - `icon`: Use the icon height (ascender to descender).  Produces more
     *   visually balanced icons that don't touch the cell edges.
     */
    enum class HeightRef : uint8_t
    {
        cell, ///< Use full cell height (for powerline/box that must tile).
        icon  ///< Use icon height (ascender to descender).
    };

    /** @brief How the glyph is scaled to fit the cell. */
    ScaleMode scaleMode { ScaleMode::none };

    /** @brief Horizontal alignment of the scaled glyph within the cell. */
    Align alignH { Align::none };

    /** @brief Vertical alignment of the scaled glyph within the cell. */
    Align alignV { Align::none };

    /**
     * @brief Reference dimension used for vertical scaling.
     *
     * `cell` uses the full cell height; `icon` uses the font's ascender-to-
     * descender span.
     */
    HeightRef heightRef { HeightRef::cell };

    /**
     * @brief Fractional padding from the top cell edge (0.0 – 1.0).
     *
     * Expressed as a fraction of `cellHeight`.  Combined with `iconInset`
     * to compute the effective target height.
     */
    float padTop { 0.0f };

    /**
     * @brief Fractional padding from the left cell edge (0.0 – 1.0).
     *
     * Expressed as a fraction of `cellWidth × cellSpan`.
     */
    float padLeft { 0.0f };

    /**
     * @brief Fractional padding from the right cell edge (0.0 – 1.0).
     *
     * Expressed as a fraction of `cellWidth × cellSpan`.
     */
    float padRight { 0.0f };

    /**
     * @brief Fractional padding from the bottom cell edge (0.0 – 1.0).
     *
     * Expressed as a fraction of `cellHeight`.
     */
    float padBottom { 0.0f };

    /**
     * @brief Relative width override as a fraction of the cell width (default 1.0).
     *
     * Values < 1.0 reduce the effective target width before scaling.
     * Currently reserved for future use; not applied in `rasterizeGlyph()`.
     */
    float relativeWidth { 1.0f };

    /**
     * @brief Relative height override as a fraction of the cell height (default 1.0).
     *
     * Values < 1.0 reduce the effective target height before scaling.
     * Currently reserved for future use; not applied in `rasterizeGlyph()`.
     */
    float relativeHeight { 1.0f };

    /**
     * @brief Relative X position offset as a fraction of the cell width (default 0.0).
     *
     * Positive values shift the glyph right.  Currently reserved for future
     * use; not applied in `rasterizeGlyph()`.
     */
    float relativeX { 0.0f };

    /**
     * @brief Relative Y position offset as a fraction of the cell height (default 0.0).
     *
     * Positive values shift the glyph up.  Currently reserved for future use;
     * not applied in `rasterizeGlyph()`.
     */
    float relativeY { 0.0f };

    /**
     * @brief Maximum allowed aspect ratio (width / height) after scaling.
     *
     * When > 0, the horizontal scale factor is clamped so that the scaled
     * glyph's aspect ratio does not exceed this value.  Set to 0 to disable
     * the clamp.
     *
     * @par Example
     * A value of 1.0 prevents the glyph from becoming wider than it is tall.
     */
    float maxAspectRatio { 0.0f };

    /**
     * @brief Maximum number of terminal cells this icon may span horizontally.
     *
     * Used by the renderer to decide whether to attempt a 2-cell layout for
     * wide icons.  Default is 2 (most NF icons can span up to 2 cells).
     */
    uint8_t maxCellSpan { 2 };

    /**
     * @brief Fractional inset applied on all four sides before padding (≈ 6.18 %).
     *
     * Provides a small breathing room between the icon and the cell edge.
     * The value is the golden ratio conjugate (1/φ²), chosen to give
     * aesthetically balanced margins.
     *
     * @note Applied in addition to the per-side `pad*` values.
     */
    static constexpr float iconInset { 0.0618f };

    /**
     * @brief Return `true` if this constraint applies any transformation.
     *
     * A constraint is inactive when `scaleMode == ScaleMode::none`.  Inactive
     * constraints are skipped by `rasterizeGlyph()`, which falls through to
     * the standard glyph rendering path.
     *
     * @return `true` if `scaleMode != ScaleMode::none`.
     */
    bool isActive() const noexcept { return scaleMode != ScaleMode::none; }
};

static_assert (std::is_trivially_copyable_v<Constraint>, "jreng::Glyph::Constraint must be trivially copyable");

/**
 * @brief Look up the constraint for a Unicode codepoint.
 *
 * Returns the `Constraint` record for the given codepoint from the
 * generated lookup table in `gen/GlyphConstraintTable.cpp`.  For codepoints
 * that are not Nerd Font icons, a default-constructed (inactive) constraint
 * is returned.
 *
 * @param codepoint Unicode codepoint to look up.
 * @return The constraint for the codepoint, or a default `Constraint`
 *         with `scaleMode == ScaleMode::none` if not found.
 *
 * @note Implemented in `constraint/jreng_glyph_constraint_table.cpp` (generated file — do
 *       not edit manually).
 * @see Constraint::isActive()
 * @see jreng::Glyph::Packer::rasterizeGlyph()
 */
// Lookup constraint for a codepoint. Returns default (inactive) constraint
// for codepoints that are not Nerd Font icons.
// Implemented in constraint/jreng_glyph_constraint_table.cpp (generated).
Constraint getConstraint (uint32_t codepoint) noexcept;

} // namespace jreng::Glyph
